import React from 'react';
import { Bot, Crown, Download, Link2, Plus, Trash2, Unlink2, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { api, botQuery, downloadFile, uploadFile, type Account, type Master } from '../api';
import { Busy, Empty, SectionTitle, Select, useConfirm } from '../ui';

type Props = { token: string; bot: string; accounts: Account[]; selectBot: (hash: string) => void; notify: (message: string, error?: boolean) => void };
type Relation = { master: string; slave: string; masterOnline?: boolean; slaveOnline?: boolean };
type Relations = { available: boolean; relations: Relation[] };
export function AccountsPage({ token, bot, accounts, selectBot, notify }: Props) {
  const confirm = useConfirm();
  const [masters, setMasters] = React.useState<Master[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [newId, setNewId] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const [relations, setRelations] = React.useState<Relations>({ available: false, relations: [] });
  const [masterBot, setMasterBot] = React.useState('');
  const [slaveBot, setSlaveBot] = React.useState('');
  const [sourceBot, setSourceBot] = React.useState('');
  const [zipFile, setZipFile] = React.useState<File | null>(null);
  const [zipSource, setZipSource] = React.useState('');
  const current = accounts.find(account => account.hash === bot);
  const load = React.useCallback(async () => { if (bot === 'unity') { setMasters([]); setLoading(false); return; } setLoading(true); try { setMasters((await api<{ masters: Master[] }>(`/api/masters${botQuery(bot)}`, token)).masters); } catch (cause) { notify((cause as Error).message, true); } finally { setLoading(false); } }, [bot, token, notify]);
  React.useEffect(() => { void load(); }, [load]);
  React.useEffect(() => { void api<Relations>('/api/relations', token).then(setRelations).catch(cause => notify((cause as Error).message, true)); }, [token, notify]);
  const change = async (action: 'add' | 'remove', id: string) => { setBusy(true); try { const result = await api<{ value: Master[] }>('/api/masters', token, { bot, action, id }); setMasters(result.value); setNewId(''); notify(action === 'add' ? '骰主已添加' : '骰主已移除'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const changeRelation = async (action: 'link' | 'unlink', slave: string, master?: string) => { setBusy(true); try { const result = await api<{ value: Relations }>('/api/relations', token, { bot: 'unity', action, slave, master }); setRelations(result.value); notify(action === 'link' ? '账号已关联' : '账号关联已取消'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const copyData = async () => { if (!sourceBot || bot === 'unity' || !(await confirm('将源账号数据复制到当前账号？系统会先备份目标账号现有数据。', { confirmLabel: '复制' }))) return; setBusy(true); try { const result = await api<{ value: string }>('/api/account/copy', token, { bot, source: sourceBot, target: bot }); notify(result.value); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const exportData = async () => { if (bot === 'unity') return; setBusy(true); try { await downloadFile(`/api/account/export${botQuery(bot)}`, token, `account_export_${bot}.zip`); notify('账号压缩包已下载'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const importData = async () => { if (!zipFile || !zipSource || bot === 'unity' || !(await confirm('将压缩包导入到当前账号？系统会先备份目标账号现有数据。', { confirmLabel: '导入' }))) return; setBusy(true); try { const query = `?bot=${encodeURIComponent(bot)}&source=${encodeURIComponent(zipSource)}`; const result = await uploadFile<{ value: string }>(`/api/account/import${query}`, token, zipFile); notify(result.value); setZipFile(null); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const removeMaster = async (id: string) => { if (await confirm(`确定移除骰主 ${id} 吗？`, { confirmLabel: '移除', destructive: true })) await change('remove', id); };
  const unlink = async (slave: string) => { if (await confirm('确定断开此账号关联吗？', { confirmLabel: '断开', destructive: true })) await changeRelation('unlink', slave); };
  const relationLabel = (hash: string, online: boolean | undefined) => {
    if (online === false) return `未知账号 ${hash.slice(0, 8)}…`;
    return accounts.find(account => account.hash === hash)?.label || hash;
  };
  const OfflineBadge = () => <span className="rounded-full bg-slate-200 px-2 py-0.5 text-[11px] font-medium text-slate-500 dark:bg-slate-700 dark:text-slate-300">离线</span>;
  return <><SectionTitle eyebrow="BOT ACCOUNTS" title="机器人账号" description="切换 OlivOS 当前进程中的机器人账号，维护该账号的骰主权限。" />
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-3">{accounts.filter(account => account.hash !== 'unity').length ? accounts.filter(account => account.hash !== 'unity').map(account => <Card key={account.hash} className={`border-slate-200 shadow-sm ${bot === account.hash ? 'ring-2 ring-brand-200' : ''}`}><CardContent className="flex flex-wrap items-center gap-4 p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Bot className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate font-semibold">{account.platform} · {account.id}</h3>{bot === account.hash && <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[11px] font-medium text-emerald-700">当前账号</span>}</div><p className="mt-1 text-xs text-slate-500">{account.model || '未指定模型'} · {account.hash}</p></div><Button size="sm" variant={bot === account.hash ? 'secondary' : 'outline'} onClick={() => selectBot(account.hash)}>{bot === account.hash ? '管理中' : '管理账号'}</Button></CardContent></Card>) : <Empty title="OlivOS 当前没有机器人账号" detail="请先在 OlivOS 中配置并启动账号。" />}</div>
      <Card className="h-fit border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-center gap-2"><Crown className="h-5 w-5 text-amber-500" /><h3 className="font-semibold">骰主列表</h3></div><p className="mt-2 text-sm text-slate-500">{current && bot !== 'unity' ? `管理 ${current.platform} · ${current.id} 的骰主权限` : '请选择具体账号后管理骰主'}</p>{loading ? <Busy /> : bot === 'unity' ? <Empty title="请选择机器人账号" /> : <><form className="mt-5 flex gap-2" onSubmit={event => { event.preventDefault(); void change('add', newId.trim()); }}><Input inputMode="numeric" pattern="[0-9]+" maxLength={32} placeholder="输入数字用户 ID" value={newId} onChange={event => setNewId(event.target.value)} /><Button disabled={busy || !/^\d+$/.test(newId.trim())}><Plus className="h-4 w-4" /><span className="sr-only">添加骰主</span></Button></form><div className="mt-5 space-y-2">{masters.length ? masters.map(master => <div key={master.id} className="flex items-center gap-3 rounded-lg border bg-slate-50 px-3 py-2.5"><div className="min-w-0 flex-1"><div className="text-sm font-medium">{master.id}</div><div className="text-xs text-slate-500">{master.platform}</div></div><Button size="icon" variant="ghost" aria-label={`移除骰主 ${master.id}`} onClick={() => void removeMaster(master.id)} disabled={busy}><Trash2 className="h-4 w-4 text-rose-500" /></Button></div>) : <Empty title="暂无骰主" detail="输入用户 ID 后添加。" />}</div></>}</CardContent></Card></div>
    <Card className="mt-5 border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-center gap-2"><Link2 className="h-5 w-5 text-brand-600" /><h3 className="font-semibold">账号主从关系</h3></div><p className="mt-1 text-sm text-slate-500">让从账号复用主账号的数据；一个从账号只能关联一个主账号。已停用账号的关联仍会显示，方便重新启用后链接或直接断开。</p>{!relations.available ? <div className="mt-4 rounded-lg bg-amber-50 p-4 text-sm text-amber-800">加载 OlivaDiceMaster 后可管理账号关系。</div> : <><div className="mt-5 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Select ariaLabel="主账号" value={masterBot} onChange={setMasterBot} placeholder="选择主账号" options={[{ value: '', label: '选择主账号' }, ...accounts.filter(account => account.hash !== 'unity').map(account => ({ value: account.hash, label: account.label }))]} /><Select ariaLabel="从账号" value={slaveBot} onChange={setSlaveBot} placeholder="选择从账号" options={[{ value: '', label: '选择从账号' }, ...accounts.filter(account => account.hash !== 'unity').map(account => ({ value: account.hash, label: account.label }))]} /><Button disabled={busy || !masterBot || !slaveBot || masterBot === slaveBot} onClick={() => void changeRelation('link', slaveBot, masterBot)}><Plus className="mr-2 h-4 w-4" />建立关联</Button></div><div className="mt-5 space-y-2">{relations.relations.length ? relations.relations.map(item => <div key={`${item.master}:${item.slave}`} className="flex flex-wrap items-center gap-3 rounded-lg border bg-slate-50 px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-800/60"><span className="font-medium">{relationLabel(item.master, item.masterOnline)}</span>{item.masterOnline === false && <OfflineBadge />}<ArrowRelation /><span className="font-medium">{relationLabel(item.slave, item.slaveOnline)}</span>{item.slaveOnline === false && <OfflineBadge />}<Button size="sm" variant="ghost" className="ml-auto text-rose-600" disabled={busy} onClick={() => void unlink(item.slave)}><Unlink2 className="mr-1.5 h-4 w-4" />断开</Button></div>) : <Empty title="暂无账号关联" />}</div></>}</CardContent></Card>
    <Card className="mt-5 border-slate-200 shadow-sm"><CardContent className="p-5"><h3 className="font-semibold">账号数据迁移</h3><p className="mt-1 text-sm text-slate-500">目标账号为当前选择的账号；导入前 OlivaDiceMaster 会自动备份目标账号已有数据。</p>{bot === 'unity' ? <Empty title="请先选择目标账号" /> : <div className="mt-5 grid gap-5 lg:grid-cols-3"><div className="space-y-3 rounded-xl border bg-slate-50 p-4"><div className="text-sm font-semibold">从其他账号复制</div><Select ariaLabel="数据源账号" value={sourceBot} onChange={setSourceBot} placeholder="选择源账号" options={[{ value: '', label: '选择源账号' }, ...accounts.filter(account => account.hash !== 'unity' && account.hash !== bot).map(account => ({ value: account.hash, label: account.label }))]} /><Button size="sm" disabled={busy || !sourceBot || !relations.available} onClick={() => void copyData()}>复制到当前账号</Button></div><div className="space-y-3 rounded-xl border bg-slate-50 p-4"><div className="text-sm font-semibold">导出账号压缩包</div><p className="text-xs text-slate-500">打包当前账号的数据目录供跨平台迁移。</p><Button size="sm" variant="outline" disabled={busy || !relations.available} onClick={() => void exportData()}><Download className="mr-2 h-4 w-4" />下载 ZIP</Button></div><div className="space-y-3 rounded-xl border bg-slate-50 p-4"><div className="text-sm font-semibold">从压缩包导入</div><Input type="file" accept=".zip,application/zip" aria-label="账号压缩包" onChange={event => { const file = event.target.files?.[0] || null; setZipFile(file); const match = file?.name.match(/^account_(?:export_|import_)?([a-zA-Z0-9_-]+)\.zip$/); if (match) setZipSource(match[1]); }} /><Input aria-label="压缩包原账号 Hash" placeholder="压缩包原账号 Hash" value={zipSource} onChange={event => setZipSource(event.target.value)} /><Button size="sm" disabled={busy || !relations.available || !zipFile || !zipSource} onClick={() => void importData()}><Upload className="mr-2 h-4 w-4" />导入当前账号</Button></div></div>}</CardContent></Card>
  </>;
}
function ArrowRelation() { return <span className="text-xs text-slate-400">主 → 从</span>; }
