import React from 'react';
import { Archive, Download, RotateCcw, Save, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { api, readJsonFile, saveJsonFile, type BackupState } from '../api';
import { Busy, SectionTitle, useConfirm } from '../ui';

type Props = { token: string; notify: (message: string, error?: boolean) => void };
type Settings = { isBackup: number; startDate: string; passDay: number; backupTime: string; maxBackupCount: number };
const normalize = (value: BackupState['settings']): Settings => ({ isBackup: value.isBackup ?? 0, startDate: value.startDate ?? '', passDay: value.passDay ?? 1, backupTime: value.backupTime ?? '04:00:00', maxBackupCount: value.maxBackupCount ?? 1 });
export function BackupPage({ token, notify }: Props) {
  const confirm = useConfirm();
  const [state, setState] = React.useState<BackupState | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [busy, setBusy] = React.useState(false);
  const [draft, setDraft] = React.useState<Settings>({ isBackup: 0, startDate: '', passDay: 1, backupTime: '04:00:00', maxBackupCount: 1 });
  const inputRef = React.useRef<HTMLInputElement>(null);
  const load = React.useCallback(async () => { setLoading(true); try { const value = await api<BackupState>('/api/backup', token); setState(value); setDraft(normalize(value.settings)); } catch (cause) { notify((cause as Error).message, true); } finally { setLoading(false); } }, [token, notify]);
  React.useEffect(() => { void load(); }, [load]);
  const save = async () => { setBusy(true); try { const value = await api<{ value: BackupState }>('/api/backup', token, { bot: 'unity', settings: draft }); setState(value.value); notify('备份计划已保存'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const manage = async (action: string, data?: unknown, key?: string) => { setBusy(true); try { const value = await api<{ value: BackupState }>('/api/backup/manage', token, { bot: 'unity', action, data, key }); setState(value.value); setDraft(normalize(value.value.settings)); notify('备份配置已更新'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const importFile = async (file?: File) => { if (!file) return; try { const data = await readJsonFile(file); if (await confirm('导入备份配置并覆盖当前计划？', { confirmLabel: '导入' })) await manage('import', data); } catch (cause) { notify((cause as Error).message, true); } if (inputRef.current) inputRef.current.value = ''; };
  const resetKey = async (key: string) => { if (await confirm(`恢复 ${key} 的默认值？`, { confirmLabel: '恢复' })) await manage('reset-key', undefined, key); };
  const confirmManage = async (message: string, action: string, destructive = false) => { if (await confirm(message, { confirmLabel: action === 'reload' ? '重新加载' : '恢复', destructive })) await manage(action); };
  return <><SectionTitle eyebrow="BACKUP PLAN" title="备份计划" description="编辑 OlivaDiceMaster 的备份计划，配置保存在青果骰核心目录。" />{loading ? <Busy /> : !state?.available ? <Card className="border-amber-200 bg-amber-50"><CardContent className="flex gap-3 p-6 text-sm text-amber-900"><Archive className="h-5 w-5 shrink-0" /><div><div className="font-semibold">未加载 OlivaDiceMaster</div><p className="mt-1 text-amber-800">自动备份依赖 OlivaDiceMaster。加载此插件后重新打开页面即可管理。</p></div></CardContent></Card> : <>
    <div className="mb-5 flex flex-wrap gap-2"><input ref={inputRef} type="file" accept=".json,application/json" className="hidden" onChange={event => void importFile(event.target.files?.[0])} /><Button size="sm" variant="outline" onClick={() => inputRef.current?.click()} disabled={busy}><Upload className="mr-2 h-4 w-4" />导入配置</Button><Button size="sm" variant="outline" onClick={() => saveJsonFile(state.settings, 'olivadice-backup.json')}><Download className="mr-2 h-4 w-4" />导出配置</Button><Button size="sm" variant="outline" onClick={() => void confirmManage('从磁盘重新加载备份配置？', 'reload')} disabled={busy}><RotateCcw className="mr-2 h-4 w-4" />从磁盘刷新</Button><Button size="sm" variant="outline" className="text-rose-600" onClick={() => void confirmManage('恢复全部备份配置为默认值？', 'reset', true)} disabled={busy}>恢复全部默认</Button></div>
    <Card className="max-w-2xl border-slate-200 shadow-sm"><CardContent className="space-y-5 p-6"><div className="flex items-center justify-between border-b pb-5"><div><div className="font-medium">启用自动备份</div><p className="mt-1 text-xs text-slate-500">由 OlivaDiceMaster 按计划执行</p></div><div className="flex items-center gap-2"><Button size="icon" variant="ghost" title="恢复备份开关默认值" onClick={() => void resetKey('isBackup')}><RotateCcw className="h-3.5 w-3.5" /></Button><Switch aria-label="启用自动备份" checked={draft.isBackup === 1} onCheckedChange={value => setDraft(current => ({ ...current, isBackup: value ? 1 : 0 }))} /></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="开始日期" reset={() => void resetKey('startDate')}><Input type="date" value={draft.startDate} onChange={event => setDraft(current => ({ ...current, startDate: event.target.value }))} /></Field><Field label="执行时间" reset={() => void resetKey('backupTime')}><Input type="time" step="1" value={draft.backupTime} onChange={event => setDraft(current => ({ ...current, backupTime: event.target.value.length === 5 ? `${event.target.value}:00` : event.target.value }))} /></Field><Field label="间隔天数" reset={() => void resetKey('passDay')}><Input type="number" min={1} max={365} value={draft.passDay} onChange={event => setDraft(current => ({ ...current, passDay: Number(event.target.value) }))} /></Field><Field label="最多保留份数" reset={() => void resetKey('maxBackupCount')}><Input type="number" min={1} max={100} value={draft.maxBackupCount} onChange={event => setDraft(current => ({ ...current, maxBackupCount: Number(event.target.value) }))} /></Field></div><div className="flex justify-end border-t pt-5"><Button onClick={() => void save()} disabled={busy || JSON.stringify(draft) === JSON.stringify(normalize(state.settings))}><Save className="mr-2 h-4 w-4" />保存计划</Button></div></CardContent></Card>
  </>}</>;
}
function Field({ label, reset, children }: { label: string; reset: () => void; children: React.ReactNode }) { return <div><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium">{label}</span><Button size="icon" variant="ghost" title={`恢复${label}默认值`} onClick={reset}><RotateCcw className="h-3.5 w-3.5" /></Button></div>{children}</div>; }
