import React from 'react';
import { DownloadCloud, Files, FolderOpen, Layers3, RotateCcw, Trash2, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { api, botQuery, uploadFile, type Deck } from '../api';
import { Busy, Empty, SearchField, SectionTitle } from '../ui';

type Props = { token: string; bot: string; notify: (message: string, error?: boolean) => void };
type FileEntry = { name: string; kind: string; size: number; scope: string };
type MarketEntry = { name: string; kind: string; author: string; version: string; description: string };
const kindLabel: Record<string, string> = { classic: 'JSON', yaml: 'YAML', excel: 'Excel' };
const detectKind = (name: string) => /\.json5?$/i.test(name) ? 'classic' : /\.ya?ml$/i.test(name) ? 'yaml' : /\.xlsx?$/i.test(name) ? 'excel' : '';
export function DecksPage({ token, bot, notify }: Props) {
  const [tab, setTab] = React.useState<'loaded' | 'files' | 'market'>('loaded');
  const [decks, setDecks] = React.useState<Deck[]>([]);
  const [files, setFiles] = React.useState<FileEntry[]>([]);
  const [market, setMarket] = React.useState<{ available: boolean; decks: MarketEntry[] } | null>(null);
  const [groupCount, setGroupCount] = React.useState(0);
  const [folder, setFolder] = React.useState('');
  const [scope, setScope] = React.useState(bot);
  const [loading, setLoading] = React.useState(true);
  const [busy, setBusy] = React.useState(false);
  const [query, setQuery] = React.useState('');
  const [uploadKind, setUploadKind] = React.useState<'auto' | 'classic' | 'yaml' | 'excel'>('auto');
  const [selected, setSelected] = React.useState('');
  const fileRef = React.useRef<HTMLInputElement>(null);
  const loadIndex = React.useCallback(async () => { setLoading(true); try { const result = await api<{ decks: Deck[]; groupCount: number }>(`/api/decks${botQuery(bot)}`, token); const next = result.decks; setDecks(next); setGroupCount(result.groupCount); setSelected(current => next.some(item => item.name === current) ? current : next[0]?.name || ''); } catch (cause) { notify((cause as Error).message, true); } finally { setLoading(false); } }, [bot, token, notify]);
  const loadFiles = React.useCallback(async (target: string) => { setLoading(true); try { const [list, location] = await Promise.all([api<{ files: FileEntry[] }>(`/api/deck-files${botQuery(target)}`, token), api<{ path: string }>(`/api/deck-folder${botQuery(target)}`, token)]); setFiles(list.files); setFolder(location.path); } catch (cause) { notify((cause as Error).message, true); } finally { setLoading(false); } }, [token, notify]);
  const loadMarket = React.useCallback(async (refresh = false) => { setLoading(true); try { setMarket(await api<{ available: boolean; decks: MarketEntry[] }>(`/api/deck-market${refresh ? '?refresh=1' : ''}`, token)); } catch (cause) { notify((cause as Error).message, true); } finally { setLoading(false); } }, [token, notify]);
  React.useEffect(() => { setScope(bot); void loadIndex(); }, [bot, loadIndex]);
  React.useEffect(() => { if (tab === 'files') void loadFiles(scope); if (tab === 'market' && !market) void loadMarket(); }, [tab, scope, loadFiles, loadMarket]);
  const reload = async () => { setBusy(true); try { await api('/api/decks/reload', token, { bot }); await loadIndex(); if (tab === 'files') await loadFiles(scope); notify('牌堆已从磁盘重新加载'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const upload = async (file?: File) => { if (!file) return; const kind = uploadKind === 'auto' ? detectKind(file.name) : uploadKind; if (!kind) { notify('请选择牌堆格式，或使用 JSON、JSON5、YAML、XLSX、XLS 扩展名', true); return; } if (!window.confirm(`将 ${file.name} 安装到${scope === 'unity' ? '全局' : '当前账号'}牌堆目录？同名文件会被覆盖。`)) return; setBusy(true); try { const query = `?bot=${encodeURIComponent(scope)}&kind=${kind}&name=${encodeURIComponent(file.name)}`; await uploadFile(`/api/deck-files/upload${query}`, token, file); await loadFiles(scope); await loadIndex(); notify('牌堆文件已安装并重新加载'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); if (fileRef.current) fileRef.current.value = ''; } };
  const remove = async (file: FileEntry) => { if (!window.confirm(`删除 ${scope === 'unity' ? '全局' : '当前账号'}牌堆文件「${file.name}」？`)) return; setBusy(true); try { await api('/api/deck-files/delete', token, { bot: scope, kind: file.kind, name: file.name }); await loadFiles(scope); await loadIndex(); notify('牌堆文件已删除'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const installMarket = async (entry: MarketEntry) => { if (!window.confirm(`将市场牌堆「${entry.name}」安装到${scope === 'unity' ? '全局' : '当前账号'}？`)) return; setBusy(true); try { await api('/api/deck-market/install', token, { bot: scope, kind: entry.kind, name: entry.name }); await loadIndex(); notify('市场牌堆已安装并重新加载'); } catch (cause) { notify((cause as Error).message, true); } finally { setBusy(false); } };
  const filtered = decks.filter(deck => `${deck.name} ${deck.groups.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const active = decks.find(deck => deck.name === selected);
  const marketFiltered = (market?.decks || []).filter(entry => `${entry.name} ${entry.author} ${entry.description}`.toLowerCase().includes(query.toLowerCase()));
  return <><SectionTitle eyebrow="DECK MANAGEMENT" title="牌堆管理" description="管理运行中的牌堆、本地文件与 Extiverse 牌堆市场。" action={<Button size="sm" variant="outline" onClick={() => void reload()} disabled={busy}><RotateCcw className={`mr-2 h-4 w-4 ${busy ? 'animate-spin' : ''}`} />重新加载牌堆</Button>} />
    <div className="mb-5 flex flex-wrap gap-2 border-b pb-3">{([['loaded', '已加载'], ['files', '本地文件'], ['market', '牌堆市场']] as const).map(([id, label]) => <button key={id} onClick={() => { setTab(id); setQuery(''); }} className={`rounded-lg px-4 py-2 text-sm font-medium ${tab === id ? 'bg-brand-50 text-brand-700' : 'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</div>
    {tab !== 'loaded' && <div className="mb-4 flex flex-wrap items-center gap-2"><span className="text-sm text-slate-500">操作范围</span>{bot === 'unity' ? <span className="rounded-md border bg-white px-3 py-2 text-sm">全局</span> : <select aria-label="牌堆操作范围" value={scope} onChange={event => setScope(event.target.value)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value={bot}>当前账号</option><option value="unity">全局</option></select>}</div>}
    {tab === 'loaded' && (loading ? <Busy /> : <><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_auto]"><SearchField value={query} onChange={setQuery} placeholder="搜索牌堆或分组" /><div className="flex items-center rounded-lg border bg-white px-4 text-sm text-slate-600">已加载 {groupCount} 个分组 · {decks.length} 个来源</div></div><div className="grid min-h-[500px] gap-4 lg:grid-cols-[320px_minmax(0,1fr)]"><Card className="overflow-hidden border-slate-200 shadow-sm"><div className="max-h-[620px] overflow-y-auto p-2">{filtered.length ? filtered.map(deck => <button key={deck.name} onClick={() => setSelected(deck.name)} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left ${selected === deck.name ? 'bg-brand-50 text-brand-800 ring-1 ring-brand-200' : 'hover:bg-slate-50'}`}><Files className="h-4 w-4 shrink-0 text-brand-500" /><span className="min-w-0 flex-1 truncate text-sm font-medium">{deck.name}</span><span className="text-xs text-slate-400">{deck.count}</span></button>) : <Empty title="没有匹配的牌堆" />}</div></Card><Card className="border-slate-200 shadow-sm"><CardContent className="p-5 md:p-7">{active ? <><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Layers3 className="h-5 w-5" /></div><div><h3 className="text-xl font-semibold">{active.name}</h3><p className="mt-1 text-sm text-slate-500">{active.count} 个可抽取分组</p></div></div><div className="mt-7 border-t pt-5"><div className="mb-3 text-sm font-medium">分组列表</div>{active.groups.length ? <div className="flex flex-wrap gap-2">{active.groups.map(group => <span key={group} className="rounded-md border bg-slate-50 px-3 py-1.5 text-sm text-slate-700">{group}</span>)}</div> : <Empty title="此牌堆没有可显示的分组" />}</div></> : <Empty title="选择左侧牌堆" />}</CardContent></Card></div></>)}
    {tab === 'files' && (loading ? <Busy /> : <><div className="mb-4 rounded-lg border bg-white p-4 text-sm"><div className="flex items-center gap-2 font-medium"><FolderOpen className="h-4 w-4 text-brand-600" />服务器目录</div><code className="mt-1 block break-all text-xs text-slate-500">{folder}</code></div><div className="mb-4 flex flex-wrap gap-2"><input ref={fileRef} type="file" accept={uploadKind === 'auto' ? ".json,.json5,.yaml,.yml,.xlsx,.xls" : undefined} className="hidden" onChange={event => void upload(event.target.files?.[0])} /><select aria-label="上传牌堆格式" value={uploadKind} onChange={event => setUploadKind(event.target.value as typeof uploadKind)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value="auto">自动识别格式</option><option value="classic">JSON / JSON5</option><option value="yaml">YAML（含无扩展名）</option><option value="excel">Excel</option></select><Button size="sm" onClick={() => fileRef.current?.click()} disabled={busy}><Upload className="mr-2 h-4 w-4" />安装本地牌堆</Button><Button size="sm" variant="outline" onClick={() => void loadFiles(scope)}><RotateCcw className="mr-2 h-4 w-4" />刷新文件列表</Button></div>{files.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{files.map(file => <Card key={`${file.kind}:${file.name}`} className="border-slate-200 shadow-sm"><CardContent className="flex items-start gap-3 p-4"><Files className="mt-1 h-5 w-5 text-brand-600" /><div className="min-w-0 flex-1"><div className="break-all text-sm font-medium">{file.name}</div><div className="mt-1 text-xs text-slate-500">{kindLabel[file.kind]} · {(file.size / 1024).toFixed(1)} KiB</div></div><Button size="icon" variant="ghost" aria-label={`删除 ${file.name}`} disabled={busy} onClick={() => void remove(file)}><Trash2 className="h-4 w-4 text-rose-500" /></Button></CardContent></Card>)}</div> : <Empty title="此范围没有本地牌堆文件" detail="可以安装 JSON、YAML 或 Excel 牌堆。" />}</>)}
    {tab === 'market' && (loading ? <Busy /> : !market?.available ? <Empty title="未加载 OlivaDiceOdyssey" detail="牌堆市场依赖 OlivaDiceOdyssey 插件。" /> : <><div className="mb-4 flex gap-2"><div className="flex-1"><SearchField value={query} onChange={setQuery} placeholder="搜索牌堆名、作者或描述" /></div><Button variant="outline" onClick={() => void loadMarket(true)}><RotateCcw className="mr-2 h-4 w-4" />刷新市场</Button></div>{marketFiltered.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{marketFiltered.slice(0, 200).map(entry => <Card key={`${entry.kind}:${entry.name}`} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="break-all font-semibold">{entry.name}</div><div className="mt-1 text-xs text-slate-500">{kindLabel[entry.kind]} · {entry.author} · {entry.version}</div></div><DownloadCloud className="h-5 w-5 shrink-0 text-brand-500" /></div><p className="mt-3 line-clamp-3 min-h-12 text-sm text-slate-600">{entry.description}</p><Button className="mt-4" size="sm" variant="outline" disabled={busy} onClick={() => void installMarket(entry)}>安装到{scope === 'unity' ? '全局' : '当前账号'}</Button></CardContent></Card>)}</div> : <Empty title="没有匹配的市场牌堆" />}</>)}
  </>;
}
